# GitHub Actions Workflow: Python Code Quality

name: Python Code Quality

on:
  push:
    paths:
      - '**.py'                           # Trigger on Python file changes
      - '.github/workflows/code_quality.yml' # Trigger on workflow file changes
  pull_request:
    paths:
      - '**.py'
      - '.github/workflows/code_quality.yml'

jobs:
  code-quality:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      # ---------------------------
      # Install dependencies/tools
      # ---------------------------
      - name: Upgrade pip and install Ruff
        run: |
          python -m pip install --upgrade pip
          pip install ruff

      - name: Install Bandit
        run: pip install bandit

      - name: Install Pyright
        run: pip install pyright

      - name: Install Isort
        run: pip install isort

      # ---------------------------
      # Run code quality checks
      # ---------------------------
      - name: Run Ruff (Lint)
        run: ruff .

      - name: Run Bandit (Security Check)
        run: bandit -r .

      - name: Run Pyright (Static Type Checking)
        run: pyright .

      - name: Run Isort (Import Sorting)
        run: isort --check-only .