$ GitHub Actions Workflow: Generate code coverage reports using coverage.py

name: Code Coverage Report
on:
  push:
    paths:
      - '**.py'                           # Trigger on Python file changes
      - '.github/workflows/coverage.yml'  # Trigger on workflow file changes
  pull_request:
    paths:
      - '**.py'
      - '.github/workflows/coverage.yml'
jobs:
  coverage-report:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      # Install dependencies
      - name: Install dependencies
        run: pip install coverage

      # Run tests with coverage
      - name: Run tests with coverage
        run: |
          coverage run -m unittest discover
          coverage report
          coverage html