name: Release

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
  workflow_dispatch:

permissions:
  contents: write

jobs:
  publish-cargo:
    name: Publish to Cargo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Publish to crates.io
        run: cargo publish --token ${{ secrets.CARGO_REGISTRY_TOKEN }}

  publish-binaries:
    name: Publish binaries
    runs-on: ${{ matrix.build.os }}
    needs: publish-cargo
    strategy:
      fail-fast: false
      matrix:
        build:
          - { NAME: linux-x64-glibc, OS: ubuntu-22.04, TARGET: x86_64-unknown-linux-gnu }
          - { NAME: linux-x64-musl, OS: ubuntu-22.04, TARGET: x86_64-unknown-linux-musl }
          - { NAME: linux-arm64-glibc, OS: ubuntu-22.04, TARGET: aarch64-unknown-linux-gnu }
          - { NAME: win32-x64-msvc, OS: windows-latest, TARGET: x86_64-pc-windows-msvc }
          - { NAME: darwin-x64, OS: macos-15, TARGET: x86_64-apple-darwin }
          - { NAME: darwin-arm64, OS: macos-15, TARGET: aarch64-apple-darwin }

    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.build.TARGET }}

      - name: Install cross
        if: runner.os == 'Linux'
        run: cargo install cross --git https://github.com/cross-rs/cross

      - name: Build and prepare (Unix)
        if: runner.os != 'Windows'
        shell: bash
        run: |
          VERSION=$(echo "${{ github.ref_name }}" | sed 's/^v//')
          
          # Build
          if [[ "${{ runner.os }}" == "Linux" ]]; then
            cross build --release --target ${{ matrix.build.TARGET }}
          else
            cargo build --release --target ${{ matrix.build.TARGET }}
          fi
          
          # Copy binary
          BINARY="gh-templates"
          cp target/${{ matrix.build.TARGET }}/release/$BINARY .
          chmod +x $BINARY
          
          # Create packages
          mkdir -p npm/bin python/gh_templates_bin
          cp $BINARY npm/bin/
          cp $BINARY python/gh_templates_bin/
          
          # npm package.json - using single package name with OS detection
          cat > npm/package.json << EOF
          {
            "name": "gh-templates",
            "version": "$VERSION",
            "description": "GitHub Templates CLI tool",
            "bin": { "gh-templates": "./bin/$BINARY" },
            "files": ["bin/"],
            "license": "Apache-2.0",
            "os": ["${{ runner.os == 'Linux' && 'linux' || 'darwin' }}"],
            "cpu": ["${{ contains(matrix.build.TARGET, 'aarch64') && 'arm64' || 'x64' }}"],
            "repository": {
              "type": "git",
              "url": "https://github.com/${{ github.repository }}.git"
            }
          }
          EOF
          
          # Python setup.py - using single package name
          cat > python/setup.py << EOF
          from setuptools import setup, find_packages
          import platform
          
          # Platform-specific binary name
          binary_name = 'gh-templates'
          
          setup(
              name='gh-templates',
              version='$VERSION',
              description='GitHub Templates CLI tool',
              packages=find_packages(),
              package_data={'gh_templates_bin': ['*']},
              entry_points={'console_scripts': ['gh-templates=gh_templates_bin:main']},
              license='Apache-2.0',
              classifiers=[
                  'Development Status :: 4 - Beta',
                  'Intended Audience :: Developers',
                  'License :: OSI Approved :: Apache Software License',
                  'Programming Language :: Python :: 3',
                  'Programming Language :: Python :: 3.7',
                  'Programming Language :: Python :: 3.8',
                  'Programming Language :: Python :: 3.9',
                  'Programming Language :: Python :: 3.10',
                  'Programming Language :: Python :: 3.11',
              ],
              python_requires='>=3.7',
          )
          EOF
          
          # Python __init__.py
          cat > python/gh_templates_bin/__init__.py << 'EOF'
          import os, sys, subprocess
          def main():
              binary = os.path.join(os.path.dirname(__file__), 'gh-templates')
              if not os.path.exists(binary):
                  print(f"Error: Binary not found at {binary}")
                  sys.exit(1)
              sys.exit(subprocess.run([binary] + sys.argv[1:]).returncode)
          EOF

      - name: Build and prepare (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          $VERSION = "${{ github.ref_name }}" -replace '^v', ''
          
          # Build
          cargo build --release --target ${{ matrix.build.TARGET }}
          
          # Copy binary
          $BINARY = "gh-templates.exe"
          Copy-Item "target/${{ matrix.build.TARGET }}/release/$BINARY" .
          
          # Create packages
          New-Item -ItemType Directory -Force -Path npm/bin, python/gh_templates_bin
          Copy-Item $BINARY npm/bin/
          Copy-Item $BINARY python/gh_templates_bin/
          
          # npm package.json - using single package name
          @"
          {
            "name": "gh-templates",
            "version": "$VERSION",
            "description": "GitHub Templates CLI tool",
            "bin": { "gh-templates": "./bin/$BINARY" },
            "files": ["bin/"],
            "license": "Apache-2.0",
            "os": ["win32"],
            "cpu": ["x64"],
            "repository": {
              "type": "git",
              "url": "https://github.com/${{ github.repository }}.git"
            }
          }
          "@ | Out-File -FilePath npm/package.json -Encoding UTF8
          
          # Python setup.py - using single package name
          @"
          from setuptools import setup, find_packages
          
          setup(
              name='gh-templates',
              version='$VERSION',
              description='GitHub Templates CLI tool',
              packages=find_packages(),
              package_data={'gh_templates_bin': ['*']},
              entry_points={'console_scripts': ['gh-templates=gh_templates_bin:main']},
              license='Apache-2.0',
              classifiers=[
                  'Development Status :: 4 - Beta',
                  'Intended Audience :: Developers',
                  'License :: OSI Approved :: Apache Software License',
                  'Programming Language :: Python :: 3',
                  'Programming Language :: Python :: 3.7',
                  'Programming Language :: Python :: 3.8',
                  'Programming Language :: Python :: 3.9',
                  'Programming Language :: Python :: 3.10',
                  'Programming Language :: Python :: 3.11',
              ],
              python_requires='>=3.7',
          )
          "@ | Out-File -FilePath python/setup.py -Encoding UTF8
          
          # Python __init__.py
          @'
          import os, sys, subprocess
          def main():
              binary = os.path.join(os.path.dirname(__file__), 'gh-templates.exe')
              if not os.path.exists(binary):
                  print(f"Error: Binary not found at {binary}")
                  sys.exit(1)
              sys.exit(subprocess.run([binary] + sys.argv[1:]).returncode)
          '@ | Out-File -FilePath python/gh_templates_bin/__init__.py -Encoding UTF8

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: gh-templates*

      - name: Publish to npm
        if: matrix.build.NAME != 'linux-x64-musl'  # Skip musl to avoid duplicate publishes
        shell: bash
        run: |
          cd npm
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
          # Use --tag to publish platform-specific versions
          npm publish --access public --tag ${{ matrix.build.NAME }}

      - name: Setup Python for PyPI
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Publish to PyPI
        shell: bash
        run: |
          cd python
          # Install required dependencies
          python -m pip install --upgrade pip setuptools wheel twine
          
          # Build the package
          python setup.py sdist bdist_wheel
          
          # Configure PyPI credentials
          echo -e "[pypi]\nusername = __token__\npassword = ${{ secrets.PYPI_API_TOKEN }}" > ~/.pypirc
          
          # Upload to PyPI with platform-specific tag
          twine upload dist/* --skip-existing

  publish-npm-latest:
    name: Publish npm latest tag
    runs-on: ubuntu-latest
    needs: publish-binaries
    steps:
      - name: Publish latest tag
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
          # Point latest to the most common platform (linux-x64-glibc)
          npm dist-tag add gh-templates@$(echo "${{ github.ref_name }}" | sed 's/^v//') latest

  publish-homebrew:
    name: Update Homebrew formula
    runs-on: macos-latest
    needs: publish-binaries
    steps:
      - name: Update Homebrew formula
        run: |
          VERSION=$(echo "${{ github.ref_name }}" | sed 's/^v//')
          
          # Get release assets
          LINUX_URL="https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/gh-templates"
          DARWIN_ARM_URL="https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/gh-templates"
          DARWIN_X64_URL="https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/gh-templates"
          
          # Calculate checksums
          wget -q $LINUX_URL -O linux-binary
          wget -q $DARWIN_ARM_URL -O darwin-arm-binary
          wget -q $DARWIN_X64_URL -O darwin-x64-binary
          
          LINUX_SHA=$(shasum -a 256 linux-binary | cut -d' ' -f1)
          DARWIN_ARM_SHA=$(shasum -a 256 darwin-arm-binary | cut -d' ' -f1)
          DARWIN_X64_SHA=$(shasum -a 256 darwin-x64-binary | cut -d' ' -f1)
          
          # Clone homebrew tap
          git clone https://github.com/rafaeljohn9/homebrew-tap.git
          cd homebrew-tap
          
          # Create/update formula
          cat > Formula/gh-templates.rb << EOF
          class GhTemplates < Formula
            desc "GitHub Templates CLI tool"
            homepage "https://github.com/${{ github.repository }}"
            version "$VERSION"
            
            on_macos do
              if Hardware::CPU.arm?
                url "$DARWIN_ARM_URL"
                sha256 "$DARWIN_ARM_SHA"
              else
                url "$DARWIN_X64_URL"
                sha256 "$DARWIN_X64_SHA"
              end
            end
            
            on_linux do
              url "$LINUX_URL"
              sha256 "$LINUX_SHA"
            end
            
            def install
              bin.install "gh-templates"
            end
          end
          EOF
          
          # Commit and push
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add Formula/gh-templates.rb
          git commit -m "Update gh-templates to $VERSION"
          git push https://x-access-token:${{ secrets.HOMEBREW_GITHUB_TOKEN }}@github.com/rafaeljohn9/homebrew-tap.git