name: Update CHANGELOG

permissions:
  contents: write

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history

      - name: Install git-cliff
        uses: taiki-e/install-action@v2
        with:
          tool: git-cliff

      - name: Generate/Prepend latest to CHANGELOG.md
        run: |
          touch CHANGELOG.md
          git cliff --latest --prepend CHANGELOG.md -o temp_changelog.md
          mv temp_changelog.md CHANGELOG.md





      - name: Commit and push CHANGELOG.md
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add CHANGELOG.md
          git commit -m "chore: update CHANGELOG [skip ci]" || echo "No changes to commit"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push if not on a tag
        if: github.ref_type != 'tag'
        run: git push origin ${{ github.ref_name }}
