name: Verify Templates

on:
  pull_request:

jobs:
  verify-templates:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Run verify-templates test
        run: cargo test --test verify_templates